### ISSUE TITLE
Support generic OIDC-Provider

### ISSUE THREAD

**Issue by droid42** [metal-stack/metalctl#82]
Currently only Dex with specific federation-claim is supported, this issue aims to support more generic oidc providers, e.g. keycloak.

To stay backwards compatible, a new config-option "issuer_type: generic" for the context is necessary to indicate that the configured issuer should be treated as generic, default is dex.

Config:
```
contexts:
  genericOIDC:
    url: http://metal-api.de
    issuer_url: https://keycloak.de
    issuer_type: generic
    client_id: def456
    client_secret: abc123
```

Or you can specify the requested scopes as custom scopes:
```
contexts:
  genericOIDC:
    url: http://metal-api.de
    issuer_url: https://keycloak.de
    custom_scopes: profile,email,oidc,roles
    client_id: def456
    client_secret: abc123
```
